"""Jazzmin admin theme — alineado con la marca Nexo."""

JAZZMIN_SETTINGS = {
    "site_title": "Nexo Admin",
    "site_header": "Nexo",
    "site_brand": "Nexo TI",
    "welcome_sign": "Panel de administración Nexo",
    "copyright": "Nexo · Gestión de actividades TI",
    "search_model": ["users.User", "activities.Activity"],
    "topmenu_links": [
        {"name": "Ir a la app", "url": "http://localhost:5173", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "Abrir Nexo", "url": "http://localhost:5173", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["users", "activities", "auth"],
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.Group": "fas fa-users",
        "users": "fas fa-users-cog",
        "users.user": "fas fa-user-tie",
        "activities": "fas fa-clipboard-list",
        "activities.activity": "fas fa-list-check",
        "activities.empresa": "fas fa-building",
        "activities.proceso": "fas fa-diagram-project",
        "activities.aplicacion": "fas fa-server",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "show_ui_builder": False,
    "show_theme_chooser": False,
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "#29AFF5",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": "darkly",
    "default_theme_mode": "light",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
