# Generated by GitHub Copilot on 2026-05-25

from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(rol__isnull=True).update(rol="member")
    User.objects.filter(rol="").update(rol="member")
    User.objects.filter(is_superuser=True).update(rol="admin")
    User.objects.filter(is_staff=True).update(rol="admin")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rol",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member")],
                default="member",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_roles, migrations.RunPython.noop),
    ]
