# Generated by Django 5.1.4 on 2026-05-26 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coordinador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinador'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
