# Generated by Django 5.1.4 on 2026-07-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0002_default_org'),
        ('users', '0004_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('coordinator', 'Coordinador'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('rol', 'owner')), fields=('organization',), name='unique_owner_per_organization'),
        ),
    ]
