# Generated by Django 5.1.4 on 2026-07-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo_readonly',
            field=models.BooleanField(default=False),
        ),
    ]
