# Generated by Django 5.1.4 on 2026-07-26 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_waitlistsignup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='lemonsqueezy', max_length=30)),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'cliente de facturación',
                'verbose_name_plural': 'clientes de facturación',
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='lemonsqueezy', max_length=30)),
                ('provider_checkout_id', models.CharField(blank=True, default='', max_length=64)),
                ('url', models.URLField(max_length=1000)),
                ('variant_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'sesión de checkout',
                'verbose_name_plural': 'sesiones de checkout',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='lemonsqueezy', max_length=30)),
                ('event_key', models.CharField(max_length=64, unique=True)),
                ('event_name', models.CharField(max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('processed', 'Procesado'), ('ignored', 'Ignorado'), ('failed', 'Fallido')], max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'evento de webhook',
                'verbose_name_plural': 'eventos de webhook',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='lemonsqueezy', max_length=30)),
                ('provider_subscription_id', models.CharField(blank=True, default='', max_length=64)),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('trialing', 'En prueba'), ('active', 'Activa'), ('past_due', 'Pago vencido'), ('paused', 'Pausada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], max_length=20)),
                ('provider_status', models.CharField(blank=True, default='', max_length=40)),
                ('plan', models.CharField(default='cloud', max_length=20)),
                ('variant_id', models.CharField(blank=True, default='', max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('customer_portal_url', models.URLField(blank=True, default='', max_length=500)),
                ('update_payment_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_subscription_id', ''), _negated=True), fields=('provider', 'provider_subscription_id'), name='unique_provider_subscription')],
            },
        ),
    ]
