# Generated by Django 5.1.4 on 2026-07-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='provider_item_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
