# Generated by Django 5.1.4 on 2026-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('proceso', models.CharField(max_length=100)),
                ('aplicacion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('stakeholder', models.CharField(max_length=100)),
                ('prioridad', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('estado', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'En progreso'), ('testing', 'En pruebas'), ('pending_client', 'Pendiente cliente'), ('done', 'Finalizado'), ('cancelled', 'Cancelado')], default='backlog', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['-pk'],
            },
        ),
    ]
