# Generated by GitHub Copilot on 2026-05-21

from django.db import migrations, models


def seed_masters_from_activities(apps, schema_editor):
    Activity = apps.get_model("activities", "Activity")
    Empresa = apps.get_model("activities", "Empresa")
    Proceso = apps.get_model("activities", "Proceso")
    Aplicacion = apps.get_model("activities", "Aplicacion")

    for nombre in (
        Activity.objects.exclude(empresa="")
        .values_list("empresa", flat=True)
        .distinct()
    ):
        Empresa.objects.get_or_create(nombre=nombre)

    for nombre in (
        Activity.objects.exclude(proceso="")
        .values_list("proceso", flat=True)
        .distinct()
    ):
        Proceso.objects.get_or_create(nombre=nombre)

    for nombre in (
        Activity.objects.exclude(aplicacion="")
        .values_list("aplicacion", flat=True)
        .distinct()
    ):
        Aplicacion.objects.get_or_create(nombre=nombre)


def unseed_masters(apps, schema_editor):
    Empresa = apps.get_model("activities", "Empresa")
    Proceso = apps.get_model("activities", "Proceso")
    Aplicacion = apps.get_model("activities", "Aplicacion")

    Empresa.objects.all().delete()
    Proceso.objects.all().delete()
    Aplicacion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Proceso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "proceso",
                "verbose_name_plural": "procesos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Aplicacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "aplicacion",
                "verbose_name_plural": "aplicaciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.RunPython(seed_masters_from_activities, unseed_masters),
    ]
