# Generated by GitHub Copilot on 2026-05-21

from datetime import date
from django.db import migrations, models
import django.core.validators


def week_of_month(dt: date) -> int:
    day = dt.day
    if day <= 7:
        return 1
    if day <= 14:
        return 2
    if day <= 21:
        return 3
    if day <= 28:
        return 4
    return 5


def backfill_planning_fields(apps, schema_editor):
    Activity = apps.get_model("activities", "Activity")
    for activity in Activity.objects.all():
        if activity.mes_planeacion and activity.semana_planeacion:
            continue
        fecha = activity.fecha_inicio or activity.fecha_limite
        if not fecha:
            continue
        activity.mes_planeacion = activity.mes_planeacion or fecha.strftime("%Y-%m")
        activity.semana_planeacion = activity.semana_planeacion or week_of_month(fecha)
        activity.save(update_fields=["mes_planeacion", "semana_planeacion"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_activity_masters"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="mes_planeacion",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="semana_planeacion",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.RunPython(backfill_planning_fields, noop_reverse),
    ]
