# Generated by GitHub Copilot on 2026-05-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_created_by(apps, schema_editor):
    Activity = apps.get_model("activities", "Activity")
    for activity in Activity.objects.filter(created_by__isnull=True):
        activity.created_by = activity.responsable
        activity.save(update_fields=["created_by"])


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_activity_planning_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_created_by, migrations.RunPython.noop),
    ]
