# Generated by Django 5.1.4 on 2026-07-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='proyecto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
