# Generated by Django 5.1.4 on 2026-07-18 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_org'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_usos', models.PositiveIntegerField(blank=True, null=True)),
                ('usos', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_codes_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'código de acceso',
                'verbose_name_plural': 'códigos de acceso',
                'ordering': ['-created_at'],
            },
        ),
    ]
