# Generated by Django 5.1.4 on 2026-09-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='next_project_numero',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
